### ISSUE TITLE
PaulaMachado - Project2

### ISSUE THREAD

**Issue by paulaRMachado** [Ironhack-data-bcn-april-2023/project-II-pipelines#4]
https://github.com/paulaRMachado/horror_movies.git

**Comment by ta-data-bcn** [comment]
Hi Paula MII! 🚀
First of all, I just wanted to say congratulations on your hard job!!!! Apart from the feedback of your presentation i'll try to give you a bit more.

 **Repository Organization**  📚
- The organization of the repo is really good, everything is tidy and in the corresponding folders. 
- There’s nothing really that I would change about the organization of the repo! Congrats!


**README.md** 📖
- I really like how you state the task at hand and how you are going to proceed.
- It is a good readme, I can understand what you did and how you did it, but I might be missing some info about the procedures you undertook to clean and filter your data.


**The code** 👩‍💻
- You have very nicely modularized your code into functions, used them and your code is clean. 
- You are getting good at it!!!!! KEEP GOING even if your computer give you issues

**Visualization** 🎨
- Its good that you used plotly and did some very interesting graphs!!!!!
- In general, very interesting and self-explaining graphs so good job!!!!!!!


Just to finish, I’ve seen that for both projects you have started working straight away, with no clear goal in mind. I recommend that you take some time and think about what you want to answer first and base your exploration on that. Because if not you can get very stuck with some things that in the end you might not even use! So i’d recommend to set yourself some research questions before you start and try and solve those questions.
